# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties

# The Minecraft version must agree with the Forge version to get a valid artifact
minecraft_version=26.1-pre-3
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[26.1, 26.2)

## Neo
# The neo version must agree with the Minecraft version to get a valid artifact
neo_version=26.1.0.0-alpha.15+pre-3
# The neo version range can use any version of neo as bounds or match the loader version range
neo_version_range=[=26.1.0.0-alpha,)
# The loader version range can only use the major version of Neo/FML as bounds
neo_loader_version_range=[3,)
moddevgradle_version=2.0.140

## Forge
# The Forge version must agree with the Minecraft version to get a valid artifact
forge_version=61.0.3
# The Forge version range can use any version of Forge as bounds or match the loader version range
forge_version_range=[61.0.3,)
# The loader version range can only use the major version of Forge/FML as bounds
forge_loader_version_range=[61,)
forgegradle_version=[6.0.46,6.2)

## Fabric
fabric_version=0.143.14+26.1
fabric_loader_version=0.18.4
org.gradle.configuration-cache=false
loom_version=1.15-SNAPSHOT

## Misc
mixin_version=0.8.5
jsr305_version=3.0.1

## Mod Properties
group=com.klikli_dev
mod_id=modonomicon
mod_name=Modonomicon
mod_license=MIT AND CC-BY-4.0
mod_version=1.126.0
mod_authors=Kli Kli
mod_description=Data-driven minecraft in-game documentation with progress visualization.

## Dependency Properties

# Mods
jei_version=19.8.5.118
jei_version_range=[19.8.2.0,)
patchouli_version=TODO
patchouli_version_range=TODO
#[1.20.2-XY-NEO,)

# Libraries
commonmark_version=0.22.0
fiber_version=0.23.0-2
